### ISSUE TITLE
About possible collaboration

### ISSUE THREAD

**Issue by castarco** [jywarren/spectral-workbench#255]
Hello,

I'm developing a very simple open source library to manage light spectrums and colour spaces in C# , and I'm thinking about possible connections with this project.

Has Spectral-Workbench a public API to send or retrieve spectrums?

On the other hand, I'm also developing a propietary program to manage spectrums and "videos" of spectrums in order to send them to LED lamps capable of reproducing a large variety of spectrums. Because my program has the ability to modify videos and also spectrums, I've developed a simple format (based on JSON) that not only contains the data points of the spectrums, but also a description and other interesting metadata (mainly "lamp fittings" data).

Are you interested in this?

Thanks for your attention :) .

**Comment by jywarren** [comment]
It does indeed, although it's not super well documented. You can see some here: https://github.com/publiclab/spectral-workbench/blob/master/config/routes.rb

I've also just created an issue for an API here: https://github.com/publiclab/spectral-workbench/issues/84

I'm closing this because we're now tracking issues at the publiclab repo: https://github.com/publiclab/spectral-workbench/issues/
